services:
  neo4j:
    image: neo4j:5.26-community
    container_name: threat-modeling-neo4j
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      # ⚠️ ATENÇÃO: Defina NEO4J_PASSWORD no seu arquivo .env.local
      # A senha abaixo é APENAS para desenvolvimento local e DEVE SER ALTERADA
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-change_this_password_immediately}
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD:-change_this_password_immediately}", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local  
  neo4j_plugins:
    driver: local
