version: '3.8'

services:
  neo4j:
    image: neo4j:5.14.0-community
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./import:/var/lib/neo4j/import
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol (for queries)
    environment:
      - NEO4J_AUTH=neo4j/s3nh4forte
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "s3nh4forte", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
