name: vet OSS Components

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Required for actions/checkout@v4
  contents: read

  # Required for writing pull request comment
  issues: write
  pull-requests: write

  # Required for uploading findings to Github security tab
  security-events: write

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run vet
        id: vet
        uses: safedep/vet-action@v1
        with:
          # Path to the policy file.
          # Remove following line to use the default policy
          policy: .github/vet/policy.yml
        env:
          # Required for writing pull request comment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Comment the below upload action if you are using
      # private repository and Code Scanning is not available
      # for your Github subscription
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ steps.vet.outputs.report != '' }}
        with:
          sarif_file: ${{ steps.vet.outputs.report }}
          category: vet
